// Create a program where the user has to guess a random number (generated by the script)
// Script must keep looping and prompt  the user to type in the number until they guess correctly
// Generate a number 1 - 10 and record how many attempts it takes the user to guess the correct number
// Print the number of attempts it took to find the correct number
// Use a for loop

var randomNumber = Math.floor(Math.random() * 10) + 1;
var userNumberString = "";
var userNumber = -1;
var attempts = 1;

for (attempts = 0; randomNumber !== userNumber; attempts++)
{
    userNumberString = prompt("Guess the number");
    userNumber = parseInt(userNumberString);
}

document.write("<h1>Congratulations!</h1><p>The correct answer was " + randomNumber + ".</p><p>It took you " + attempts + " attempts to guess the random number!</p>");